Front end structure
learn-academy-2022-hotel/cat-tinder-frontend-team-cats-rule-dogs-drool pull request #1
Opened 2023-02-01 00:44 UTC by msawhitney

2023-02-01 01:51 UTC, triciasykes commented on src/App.js
> +};
Hey - you don't have to use the divs for header and footers in App.js.  Remember, these are components, so any structure you'd like those things to have will live in their component files (i.e. Header.js/Footer.js).

2023-02-01 01:51 UTC, triciasykes requested changes
please see comment below.  You're almost there!

2023-02-01 16:30 UTC, msawhit commented on src/App.js
> +};
Thank you. We will work on that :)

2023-02-02 18:21 UTC, triciasykes approved these changes

2023-02-02 18:36 UTC, merged